/*

Extra small
Small
Medium
Large
Extra large
Full
*/

import { SHAPE_TOKENS } from "../../builders/shapeBuilder";


export const SHAPES={
EXTRA_SMALL_ROUNDING:'EXTRA_SMALL_ROUNDING',
SMALL_ROUNDING:'SMALL_ROUNDING',
MEDUIM_ROUNDING:'MEDUIM_ROUNDING',
LARGE_ROUNDING:'LARGE_ROUNDING',
EXTRA_LARGE_ROUNDING:'EXTRA_LARGE_ROUNDING',
FULL_ROUNDED:'FULL_ROUNDED',

EXTRA_SMALL_START_ROUNDING:'EXTRA_SMALL_START_ROUNDING',
SMALL_START_ROUNDING:'SMALL_START_ROUNDING',
MEDUIM_START_ROUNDING:'MEDUIM_START_ROUNDING',
LARGE_START_ROUNDING:'LARGE_START_ROUNDING',
EXTRA_LARGE_START_ROUNDING:'EXTRA_LARGE_START_ROUNDING',

EXTRA_SMALL_END_ROUNDING:'EXTRA_SMALL_END_ROUNDING',
SMALL_END_ROUNDING:'SMALL_END_ROUNDING',
MEDUIM_END_ROUNDING:'MEDUIM_END_ROUNDING',
LARGE_END_ROUNDING:'LARGE_END_ROUNDING',
EXTRA_LARGE_END_ROUNDING:'EXTRA_LARGE_END_ROUNDING',

EXTRA_SMALL_TOP_ROUNDING:'EXTRA_SMALL_TOP_ROUNDING',
SMALL_TOP_ROUNDING:'SMALL_TOP_ROUNDING',
MEDUIM_TOP_ROUNDING:'MEDUIM_TOP_ROUNDING',
LARGE_TOP_ROUNDING:'LARGE_TOP_ROUNDING',
EXTRA_LARGE_TOP_ROUNDING:'EXTRA_LARGE_TOP_ROUNDING',

EXTRA_SMALL_BOTTOM_ROUNDING:'EXTRA_SMALL_BOTTOM_ROUNDING',
SMALL_BOTTOM_ROUNDING:'SMALL_BOTTOM_ROUNDING',
MEDUIM_BOTTOM_ROUNDING:'MEDUIM_BOTTOM_ROUNDING',
LARGE_BOTTOM_ROUNDING:'LARGE_BOTTOM_ROUNDING',
EXTRA_LARGE_BOTTOM_ROUNDING:'EXTRA_LARGE_BOTTOM_ROUNDING',
};

export const borderRadiusCss=()=>({$shape})=>`${$shape?`border-radius:${SHAPE_TOKENS[$shape]};`:''}`
