const TOKENS={
    DISPLAY:{
        LARGE:{
            weight:400,
            size:'57pt',
            spacing:'-0.25pt',
            height:'64pt',
        },
        MEDIUM:{
            weight:400,
            size:'45pt',
            spacing:'0pt',
            height:'52pt',
        },
        SMALL:{
            weight:400,
            size:'36pt',
            spacing:'0pt',
            height:'44pt',
        }
    },
    HEADLINES:{
        LARGE:{
            weight:400,
            size:'32pt',
            spacing:'0pt',
            height:'40pt',
        },
        MEDIUM:{
            weight:400,
            size:'28pt',
            spacing:'0pt',
            height:'36pt',
        },
        SMALL:{
            weight:500,
            size:'24pt',
            spacing:'0pt',
            height:'32pt', 
        }
    },
    TITLE:{
        LARGE:{
            weight:400,
            size:'22pt',
            spacing:'0pt',
            height:'28pt',
        },
        MEDIUM:{
            weight:500,
            size:'16pt',
            spacing:'0.15pt',
            height:'24pt',
        },
        SMALL:{
            weight:500,
            size:'14pt',
            spacing:'0.1pt',
            height:'20pt',
        }
    },
    BODY:{
        LARGE:{
            weight:400,
            size:'16pt',
            spacing:'0.5pt',
            height:'24pt',
        },
        MEDIUM:{
            weight:400,
            size:'14pt',
            spacing:'0.25pt',
            height:'20pt',
        },
        SMALL:{
            weight:400,
            size:'12pt',
            spacing:'0.4pt',
            height:'16pt',
        }
    },
    LABEL:{
        LARGE:{
            weight:700,
            size:'14pt',
            spacing:'0.1pt',
            height:'20pt',
        },
        MEDIUM:{
            weight:700,
            size:'12pt',
            spacing:'0.5pt',
            height:'16pt',
        },
        SMALL:{
            weight:500,
            size:'11pt',
            spacing:'0.5pt',
            height:'16pt',
        }
    }
}

export default function BuildThemeFonts({family,rootElementSize}){
   return {
    family,
    rootElementSize,
    ...TOKENS
   } 
}